# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20160416_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='end_date',
            field=models.DateField(blank=True, help_text=b'The end date to hide the data from the user in the search page', null=True),
        ),
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='satelliteinstrumentgroup',
            name='start_date',
            field=models.DateField(blank=True, help_text=b'The beginning date to hide the data from the user in the search page', null=True),
        ),
    ]
